// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF71cwYZuzcvUtS0PVEIG8BMEEos32KDg',
    appId: '1:736161840056:web:a620613d4936eae22cad4d',
    messagingSenderId: '736161840056',
    projectId: 'ldctool',
    authDomain: 'ldctool.firebaseapp.com',
    storageBucket: 'ldctool.firebasestorage.app',
    measurementId: 'G-MVBKEWCCL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc6I2PDYIZia5gVZi8o-B7yXsoavTfxm0',
    appId: '1:736161840056:android:8e29c2ecd9c1b61d2cad4d',
    messagingSenderId: '736161840056',
    projectId: 'ldctool',
    storageBucket: 'ldctool.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3mB5yySpYafJSn2dUo5XCiIolzkrykqo',
    appId: '1:736161840056:ios:ce2228101c41ae692cad4d',
    messagingSenderId: '736161840056',
    projectId: 'ldctool',
    storageBucket: 'ldctool.firebasestorage.app',
    iosBundleId: 'com.ldc.ldcTool',
  );

}